In [4]:
import pandas as  pd

In [5]:
df_laptops = pd.read_csv(r"C:\Users\krishna rawal\OneDrive\Desktop\laptop_price.csv" , encoding='latin1')

In [7]:
df_laptops.head(3)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00

# 1 Create a column based on 1 conditions: np.where()

In [8]:
import numpy as  np

In [11]:
# create an array based on price tiers

np.where(df_laptops['Price_euros'] > 2000 , 'Expensive', 'Cheap')

array(['Cheap', 'Cheap', 'Cheap', ..., 'Cheap', 'Cheap', 'Cheap'],
      dtype='<U9')

In [12]:
# Set it to a new column
df_laptops['Price_tiers']=np.where(df_laptops['Price_euros'] > 2000 , 'Expensive', 'Cheap')

In [13]:
# Show first 5 rows
df_laptops.head(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tiers
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Cheap
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Cheap

In [14]:
# count values in price_tier column
df_laptops.value_counts('Price_tiers')

Price_tiers
Cheap        1166
Expensive     137
Name: count, dtype: int64

### 1.1 Exercise

In [15]:
# create an arrat based on screen size 
np.where(df_laptops['Inches'] > 15 , 'BIG', 'small')

array(['small', 'small', 'BIG', ..., 'small', 'BIG', 'BIG'], dtype='<U5')

In [16]:
# Set it to a new  column
df_laptops['Screen_size']=np.where(df_laptops['Inches'] > 15 , 'BIG', 'small')

In [17]:
# Show first 5 rows
df_laptops.head(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tiers,Screen_size
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Cheap,small
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap,small
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap,BIG
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive,BIG
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Cheap,small

In [18]:
# Count values in screen_size column
df_laptops.value_counts('Screen_size')

Screen_size
BIG      835
small    468
Name: count, dtype: int64