In [3]:
import pandas as pd
import numpy as np

In [ ]:
!pip install pandas numpy

# Creating a dataframe from an Array

### Option1

In [4]:
#creating an array
data = np.array([[1,4],[2,4],[8,4]])

In [7]:
#creating a dataframe
df=pd.DataFrame(data)

In [8]:
# Showing the Dataframe
df

   0  1
0  1  4
1  2  4
2  8  4

### Option2

In [9]:
#creating an array
data = np.array([[11,4],[2,4],[8,9]])

In [11]:
#creating a dataframe
df = pd.DataFrame(data , index=['row1','row2','row3'],
                  columns=['col1','col2'])

In [12]:
# Showing the Dataframe
df

      col1  col2
row1    11     4
row2     2     4
row3     8     9

# Creating a DataFrame from a dictionary

In [13]:
# lists used for this example
States = ['goa' , 'rajhasthan' , 'odissa' , 'sikkim']
population = [23435545 , 5522343535, 532344234, 3423434]

In [14]:
#Storing lists within a dictionary
dict_states = {'States':States , 'population':population}

In [15]:
#Creating the dataframe
df_population=pd.DataFrame(dict_states)

In [16]:
# Showing the dataframe
df_population

       States  population
0         goa    23435545
1  rajhasthan  5522343535
2      odissa   532344234
3      sikkim     3423434

# Creating a DataFrame from a CSV file

In [26]:
#reading the csv file
df = pd.read_csv(r"C:\Users\krishna rawal\dataset.csv")

In [27]:
# show first five rows of dataframe
df.head()

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org

In [28]:
# show all rows dataframe
df

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org
...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com