In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv(r"C:\Users\krishna rawal\dataset.csv")
df_exams.head()

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org

In [5]:
import numpy as np

In [6]:
# Create random numbers for our new score columns
score1 = np.random.randint(1,100, size=1000)
score2 = np.random.randint(1,100, size=1000)

In [7]:
# Create a series using the random numbers
series1 = pd.Series(score1 , index=np.arange(0,1000))
series2 = pd.Series(score2 , index=np.arange(0,1000))

In [8]:
# USING ASSIGN() TO ADD MULTIPLE COLUMNS
df_exams = df_exams.assign(score1 = series1 ,score2 = series2)

In [9]:
# printing dataFrame
df_exams

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email,score1,score2
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com,72,13
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com,88,57
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com,98,87
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com,58,47
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org,98,78
...,...,...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org,95,84
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org,97,58
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com,21,66
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com,28,66
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com,61,68

# 1 Sort a DataFrame

In [10]:
# Sort by one column
df_exams.sort_values(by='score1')

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email,score1,score2
938,"LIVINGSTON HOSPITAL AND HEALTHCARE SERVICES, INC.",Male,Goldenrod,Software Engineer IV,670-68-8970,12/17/1984,Jingling,China,982-938-5840,lherriesq2@accuweather.com,1,6
69,CONNECTICUT CHILDREN'S MEDICAL CENTER,Male,Crimson,Geologist II,519-87-8515,1/15/1970,Huacaschuque,Peru,778-431-1907,tspellicy1x@cafepress.com,1,14
804,SOUTH SHORE HOSPITAL INC.,Male,Pink,Social Worker,465-24-5836,5/1/1997,San Antonio,United States,210-654-9842,hfardellmc@php.net,1,91
685,CARLINVILLE AREA HOSPITAL ASSOCIATION,Male,Teal,Structural Engineer,734-29-4847,10/6/1978,Bokat,Indonesia,512-955-2681,jetteryj1@wordpress.org,1,87
669,FIVE COUNTIES HOSPITAL & NURSING HOME,Female,Teal,Graphic Designer,287-43-7300,10/23/1955,Dikhil,Djibouti,104-857-0569,rburchattil@army.mil,1,75
...,...,...,...,...,...,...,...,...,...,...,...,...
74,NORTHEAST GEORGIA MEDICAL CENTER INC,Female,Red,Product Engineer,203-36-4794,11/29/1978,Agía Varvára,Greece,354-301-9756,oskuce22@ebay.co.uk,99,60
758,DAWSON COUNTY HOSPITAL DISTRICT,Male,Pink,Assistant Manager,704-77-0243,5/7/1983,Jember,Indonesia,955-116-3709,egeevel2@washington.edu,99,83
313,THE MILTON S. HERSHEY MEDICAL CENTER PHYSICIAN...,Female,Fuscia,Quality Control Specialist,827-46-3864,8/29/1989,Saint-Brieuc,France,511-430-7152,hargrave8p@fc2.com,99,86
403,ST VINCENT HOSPITAL,Male,Crimson,Account Executive,329-87-9640,9/22/1986,Palmar de Varela,Colombia,192-975-4989,kblackburnb7@bing.com,99,2
295,EAST TENNESSEE CHILDREN'S HOSPITAL ASSOCIATION...,Male,Yellow,Occupational Therapist,740-75-2889,10/29/1979,Peñal,Trinidad and Tobago,708-581-8940,jmalster87@privacy.gov.au,99,26

In [ ]:
# Sort descending by one column
df_exams.sort_values(by='score1')
df_exams.sort_values('score1')   #same

In [11]:
# Sort descending by multiple columns
df_exams.sort_values(by='score1' , ascending=False)

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email,score1,score2
74,NORTHEAST GEORGIA MEDICAL CENTER INC,Female,Red,Product Engineer,203-36-4794,11/29/1978,Agía Varvára,Greece,354-301-9756,oskuce22@ebay.co.uk,99,60
870,DAYTON OSTEOPATHIC HOSPITAL,Male,Turquoise,Design Engineer,517-09-0589,8/7/1983,Solec Nad Wisłą,Poland,171-123-3611,jsladero6@goo.gl,99,75
758,DAWSON COUNTY HOSPITAL DISTRICT,Male,Pink,Assistant Manager,704-77-0243,5/7/1983,Jember,Indonesia,955-116-3709,egeevel2@washington.edu,99,83
295,EAST TENNESSEE CHILDREN'S HOSPITAL ASSOCIATION...,Male,Yellow,Occupational Therapist,740-75-2889,10/29/1979,Peñal,Trinidad and Tobago,708-581-8940,jmalster87@privacy.gov.au,99,26
403,ST VINCENT HOSPITAL,Male,Crimson,Account Executive,329-87-9640,9/22/1986,Palmar de Varela,Colombia,192-975-4989,kblackburnb7@bing.com,99,2
...,...,...,...,...,...,...,...,...,...,...,...,...
69,CONNECTICUT CHILDREN'S MEDICAL CENTER,Male,Crimson,Geologist II,519-87-8515,1/15/1970,Huacaschuque,Peru,778-431-1907,tspellicy1x@cafepress.com,1,14
669,FIVE COUNTIES HOSPITAL & NURSING HOME,Female,Teal,Graphic Designer,287-43-7300,10/23/1955,Dikhil,Djibouti,104-857-0569,rburchattil@army.mil,1,75
172,UNIVERSITY HOSPITALS CASE MEDICAL CENTER,Female,Orange,Nurse,879-06-0751,4/11/1975,Monguno,Nigeria,516-767-6982,ytarren4s@howstuffworks.com,1,72
563,CHARLOTTE-MECKLENBURG HOSPITAL AUTHORITY,Male,Goldenrod,Engineer IV,883-08-8822,5/21/1998,Ulcinj,Montenegro,125-753-3982,smaccourtfn@dion.ne.jp,1,17
938,"LIVINGSTON HOSPITAL AND HEALTHCARE SERVICES, INC.",Male,Goldenrod,Software Engineer IV,670-68-8970,12/17/1984,Jingling,China,982-938-5840,lherriesq2@accuweather.com,1,6

In [15]:
# Sort descending by multiple columns
df_exams.sort_values(['score1','score2'], ascending=False)

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email,score1,score2
313,THE MILTON S. HERSHEY MEDICAL CENTER PHYSICIAN...,Female,Fuscia,Quality Control Specialist,827-46-3864,8/29/1989,Saint-Brieuc,France,511-430-7152,hargrave8p@fc2.com,99,86
758,DAWSON COUNTY HOSPITAL DISTRICT,Male,Pink,Assistant Manager,704-77-0243,5/7/1983,Jember,Indonesia,955-116-3709,egeevel2@washington.edu,99,83
557,HOPE MEDICAL CENTER LAB CRAIGSVILLE,Male,Blue,Clinical Specialist,746-95-0886,2/17/1961,Gobernador Ingeniero Valentín Virasoro,Argentina,563-622-2087,blidierthfh@tripadvisor.com,99,78
870,DAYTON OSTEOPATHIC HOSPITAL,Male,Turquoise,Design Engineer,517-09-0589,8/7/1983,Solec Nad Wisłą,Poland,171-123-3611,jsladero6@goo.gl,99,75
265,EASTLAND MEMORIAL HOSPITAL DISTRICT,Female,Maroon,Clinical Specialist,872-75-7729,11/26/2000,Lakeland,United States,863-844-6153,ehalversen7d@networksolutions.com,99,64
...,...,...,...,...,...,...,...,...,...,...,...,...
669,FIVE COUNTIES HOSPITAL & NURSING HOME,Female,Teal,Graphic Designer,287-43-7300,10/23/1955,Dikhil,Djibouti,104-857-0569,rburchattil@army.mil,1,75
172,UNIVERSITY HOSPITALS CASE MEDICAL CENTER,Female,Orange,Nurse,879-06-0751,4/11/1975,Monguno,Nigeria,516-767-6982,ytarren4s@howstuffworks.com,1,72
563,CHARLOTTE-MECKLENBURG HOSPITAL AUTHORITY,Male,Goldenrod,Engineer IV,883-08-8822,5/21/1998,Ulcinj,Montenegro,125-753-3982,smaccourtfn@dion.ne.jp,1,17
69,CONNECTICUT CHILDREN'S MEDICAL CENTER,Male,Crimson,Geologist II,519-87-8515,1/15/1970,Huacaschuque,Peru,778-431-1907,tspellicy1x@cafepress.com,1,14
938,"LIVINGSTON HOSPITAL AND HEALTHCARE SERVICES, INC.",Male,Goldenrod,Software Engineer IV,670-68-8970,12/17/1984,Jingling,China,982-938-5840,lherriesq2@accuweather.com,1,6

In [17]:
# Sort descending by multiple columns and update the dataframe
df_exams.sort_values(['score1','score2'], ascending=False,inplace=True)
# inplace overwrite or update the DataFrame
df_exams

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email,score1,score2
313,THE MILTON S. HERSHEY MEDICAL CENTER PHYSICIAN...,Female,Fuscia,Quality Control Specialist,827-46-3864,8/29/1989,Saint-Brieuc,France,511-430-7152,hargrave8p@fc2.com,99,86
758,DAWSON COUNTY HOSPITAL DISTRICT,Male,Pink,Assistant Manager,704-77-0243,5/7/1983,Jember,Indonesia,955-116-3709,egeevel2@washington.edu,99,83
557,HOPE MEDICAL CENTER LAB CRAIGSVILLE,Male,Blue,Clinical Specialist,746-95-0886,2/17/1961,Gobernador Ingeniero Valentín Virasoro,Argentina,563-622-2087,blidierthfh@tripadvisor.com,99,78
870,DAYTON OSTEOPATHIC HOSPITAL,Male,Turquoise,Design Engineer,517-09-0589,8/7/1983,Solec Nad Wisłą,Poland,171-123-3611,jsladero6@goo.gl,99,75
265,EASTLAND MEMORIAL HOSPITAL DISTRICT,Female,Maroon,Clinical Specialist,872-75-7729,11/26/2000,Lakeland,United States,863-844-6153,ehalversen7d@networksolutions.com,99,64
...,...,...,...,...,...,...,...,...,...,...,...,...
669,FIVE COUNTIES HOSPITAL & NURSING HOME,Female,Teal,Graphic Designer,287-43-7300,10/23/1955,Dikhil,Djibouti,104-857-0569,rburchattil@army.mil,1,75
172,UNIVERSITY HOSPITALS CASE MEDICAL CENTER,Female,Orange,Nurse,879-06-0751,4/11/1975,Monguno,Nigeria,516-767-6982,ytarren4s@howstuffworks.com,1,72
563,CHARLOTTE-MECKLENBURG HOSPITAL AUTHORITY,Male,Goldenrod,Engineer IV,883-08-8822,5/21/1998,Ulcinj,Montenegro,125-753-3982,smaccourtfn@dion.ne.jp,1,17
69,CONNECTICUT CHILDREN'S MEDICAL CENTER,Male,Crimson,Geologist II,519-87-8515,1/15/1970,Huacaschuque,Peru,778-431-1907,tspellicy1x@cafepress.com,1,14
938,"LIVINGSTON HOSPITAL AND HEALTHCARE SERVICES, INC.",Male,Goldenrod,Software Engineer IV,670-68-8970,12/17/1984,Jingling,China,982-938-5840,lherriesq2@accuweather.com,1,6

In [18]:
# sort descending with a key function
df_exams.sort_values('color' , ascending=True , key=lambda col:col.str.lower())
# note : you can sort the column as it is now , but we'll use the "key" argument to ignore case of text

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email,score1,score2
358,OAKES COMMUNITY HOSPITAL,Female,Aquamarine,Geologist I,684-09-4577,7/30/1999,Korem,Ethiopia,444-436-3528,nrockwell9y@ustream.tv,79,37
834,METHODIST MEDICAL CENTER OF ILLINOIS,Male,Aquamarine,Research Assistant I,863-45-8874,8/28/1963,Pamiers,France,155-448-4546,ssivelln6@nhs.uk,93,30
657,BROADLAWNS MEDICAL CENTER,Female,Aquamarine,Programmer III,640-54-2462,1/22/1979,Shuiquan,China,619-870-8374,fcanbyi9@pinterest.com,28,55
609,MOUNT SINAI HOSPITAL,Female,Aquamarine,Chemical Engineer,818-50-9642,2/17/1992,Komysh-Zorya,Ukraine,506-572-8299,kschultzegx@google.es,61,5
729,"RITE CHOICE MEDICAL CENTERS OF FLORIDA, INC.",Non-binary,Aquamarine,Legal Assistant,549-15-9418,12/9/1950,Itapetininga,Brazil,510-982-9811,ufretterk9@wp.com,27,46
...,...,...,...,...,...,...,...,...,...,...,...,...
858,"CALDWELL MEMORIAL HOSPITAL, INC.",Male,Yellow,Environmental Tech,868-41-7049,12/3/1965,Tambov,Russia,402-513-0442,rlidgardnu@mit.edu,22,65
254,MAT SU VALLEY MEDICAL CENTER LLC,Male,Yellow,Marketing Manager,814-97-3215,12/18/1954,Sundbyberg,Sweden,980-948-9383,sebbitt72@rediff.com,48,30
798,LOYOLA UNIVERSITY MEDICAL CENTER,Male,Yellow,Sales Associate,766-71-7061,9/23/1971,Cruzeiro,Portugal,887-815-4122,mturfsm6@apache.org,85,80
322,SPECTRUM HEALTH HOSPITALS,Male,Yellow,Teacher,612-77-4160,4/7/1990,Valdivia,Chile,244-388-4704,glambden8y@privacy.gov.au,48,81
936,MONTEFIORE MEDICAL CENTER,Female,Yellow,Senior Developer,508-40-2386,10/30/1955,Vatutino,Russia,142-255-7957,cinnotq0@naver.com,43,46