In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv(r"C:\Users\krishna rawal\dataset.csv")
df_exams.head()

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org

# 1 Rename Column

In [4]:
# rename column and overwrite values of the dataframe
df_exams=df_exams.rename(columns={'gender':'Gender'})

In [5]:
# updation of dataframe
df_exams

,hospital_name,Gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org
...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com

In [6]:
# rename multiple columns and update the dataframe with inplace argument
df_exams.rename(columns={'phone_number':'Mobile_number',
                        'city':'town',
                        'color':'Rang'})

,hospital_name,Gender,Rang,job_title,ssn,birthdate,town,country,Mobile_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org
...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com

In [7]:
# Show dataframe
df_exams # NOT UPDATED AS WE DIDN'T ASSIGN THE DATAFRAME NAME TO THE NEW MODIFIED DATA

,hospital_name,Gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org
...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com

# 2. Rename Index

In [10]:
# rename index 0 ,1 and 2 and update the dataframe
df_exams.rename(index={0:'A',1:'B',2:'C'},inplace = True)
df_exams

,hospital_name,Gender,color,job_title,ssn,birthdate,city,country,phone_number,email
A,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
B,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
C,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org
...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com

In [11]:
# Show first three Row
df_exams.head(3)

,hospital_name,Gender,color,job_title,ssn,birthdate,city,country,phone_number,email
A,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
B,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
C,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com