In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv(r"C:\Users\krishna rawal\dataset.csv")

In [3]:
# showing the dataframe
df_exams

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org
...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com

## Attributes

In [4]:
# getting access to shape attribute
df_exams.shape

(1000, 10)

In [5]:
# getting access to the index attribute
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [6]:
# getting access to the column attribute
df_exams.columns

Index(['hospital_name', 'gender', 'color', 'job_title', 'ssn', 'birthdate',
       'city', 'country', 'phone_number', 'email'],
      dtype='str')

In [8]:
# data types of each column
df_exams.dtypes

hospital_name    str
gender           str
color            str
job_title        str
ssn              str
birthdate        str
city             str
country          str
phone_number     str
email            str
dtype: object

## Methods

In [9]:
# Showing the first 5 columns
df_exams.head()

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org

In [10]:
# showing the info of the dataframe
df_exams.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   hospital_name  1000 non-null   str
 1   gender         1000 non-null   str
 2   color          1000 non-null   str
 3   job_title      1000 non-null   str
 4   ssn            1000 non-null   str
 5   birthdate      1000 non-null   str
 6   city           1000 non-null   str
 7   country        1000 non-null   str
 8   phone_number   1000 non-null   str
 9   email          1000 non-null   str
dtypes: str(10)
memory usage: 78.3 KB

In [11]:
# describing basic statistics of the dataframe
df_exams.describe()

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
unique,898,8,19,179,1000,975,974,130,1000,1000
top,MONTEFIORE MEDICAL CENTER,Male,Mauv,Desktop Support Technician,414-96-9723,8/31/1954,San Isidro,China,644-374-7372,gchansonnau0@live.com
freq,5,483,64,19,1,2,4,168,1,1

## Functions

In [13]:
# Obtaining the length of the dataframe (number of columns)
len(df_exams)

1000

In [17]:
# obtaining the highest index of the dataframe
max(df_exams.phone_number)

'999-564-5590'

In [16]:
# obtaining the lowest index of the dataframe
min(df_exams.phone_number)

'101-289-4410'

In [18]:
# obtaining the data type
type(df_exams)

pandas.DataFrame

In [19]:
# rounding the values of the dataset
round(df_exams , 2) # 2 --> round to 2 decimal point

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org
...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com