In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv(r"C:\Users\krishna rawal\dataset.csv")
df_exams.head()

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org

In [ ]:
# FOR OPERATIONS I HAVE TO ADD COLUMNS

In [3]:
import numpy as np

In [4]:
# Create random numbers for our new score columns
score1 = np.random.randint(1,100, size=1000)
score2 = np.random.randint(1,100, size=1000)

In [5]:
# Create a series using the random numbers
series1 = pd.Series(score1 , index=np.arange(0,1000))
series2 = pd.Series(score2 , index=np.arange(0,1000))

In [6]:
# USING ASSIGN() TO ADD MULTIPLE COLUMNS
df_exams = df_exams.assign(score1 = series1 ,score2 = series2)

In [7]:
# printing dataFrame
df_exams

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email,score1,score2
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com,10,37
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com,78,54
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com,99,59
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com,11,32
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org,65,15
...,...,...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org,45,98
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org,71,79
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com,11,89
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com,15,11
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com,59,92

# 1 Math operation

### 1.1 Operations on Columns

In [9]:
# Select a column and calculate total sum
df_exams['score2'].sum()

np.int64(49040)

In [14]:
# count, mean, std, max and min
df_exams['score1'].count()
df_exams['score1'].mean()
df_exams['score1'].std()      # standard deviation
df_exams['score1'].max()
df_exams['score1'].min()

1

In [15]:
# Easier Calculations with .describe()
df_exams.describe()

            score1       score2
count  1000.000000  1000.000000
mean     50.117000    49.040000
std      29.213503    28.924056
min       1.000000     1.000000
25%      24.750000    24.000000
50%      50.000000    49.000000
75%      75.000000    74.000000
max      99.000000    99.000000

### 1.2 Operations in rows

In [20]:
# Calculating the sum in a row
df_exams['score1'] + df_exams['score2']

0       47
1      132
2      158
3       43
4       80
      ...
995    143
996    150
997    100
998     26
999    151
Length: 1000, dtype: int32

In [21]:
# calculating the average score and assigning the result to a new column 
df_exams['Avg_Score'] = (df_exams['score1'] + df_exams['score2'])/2

In [22]:
# showing the DataFrame
df_exams

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email,score1,score2,Avg_Score
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com,10,37,23.5
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com,78,54,66.0
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com,99,59,79.0
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com,11,32,21.5
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org,65,15,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org,45,98,71.5
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org,71,79,75.0
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com,11,89,50.0
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com,15,11,13.0
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com,59,92,75.5